language: c

install:
    - sudo apt-get update > /dev/null
    - sudo apt-get install mono-devel > /dev/null

script:
    - ./autogen.sh MCS=/usr/bin/dmcs
    - xbuild SmartIrc4net.sln
    - make clean; make
